upstream internal {
    server nginx-internal:80;
}
server {
    listen 80;
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 512;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/javascript
        application/xml
        text/xml
        image/svg+xml;
    location / {
        proxy_pass http://internal;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}