apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  namespace: note

spec:
  serviceName: redis-service

  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
    
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379

          command:
            - redis-server

          args:
            - --appendonly
            - "yes"
            
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping

            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3 

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 128Mi

            limits:
              cpu: 300m
              memory: 512Mi
   
          volumeMounts:
              - name: redis-storage
                mountPath: /data

      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc


