apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
  namespace: note

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers: 
        - name: migrate
          image: ghcr.io/rabs1stem/notes-backend:3a0fd15aae626f1fb8ec8c36fdf305817bf1d71c 
          imagePullPolicy: IfNotPresent
          
          command:
            - alembic
            - upgrade
            - head

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            
            limits:
              cpu: 500m
              memory: 512Mi

          envFrom:
            - configMapRef:
                name: backend-config
              
            - secretRef:
                name: backend-secret