"""add theme-cyber

Revision ID: eecdf7c78c93
Revises: 75adb22acc3c
Create Date: 2026-06-11 08:06:17.133063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecdf7c78c93'
down_revision: Union[str, None] = '75adb22acc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(),
               server_default='default',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'monitor'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
