---
- name: Install docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add deploy to docker group
  user:
    name: deploy
    groups: docker
    append: true